[package]
name = "db-infra"
version.workspace = true
edition.workspace = true

[dependencies]
sea-orm = { workspace = true }
percent-encoding = "2"
num_cpus = "1.0"
thiserror = "2.0"
async-trait = "0.1"
tracing = "0.1"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
fs4 = "0.13"
rand = "0.9"
tokio = { version = "1.0", features = ["full"] }
tokio-util = "0.7"
migration = { path = "../migration" }

[lib]
path = "src/lib.rs"
