[package]
name = "migration"
edition.workspace = true
version.workspace = true

[lib]

[dependencies]
sea-orm-migration = { version = "1.1", features = ["runtime-tokio-rustls", "sqlx-postgres", "sqlx-sqlite", "with-time"] }
async-trait = "0.1"
tracing = "0.1"
