[package]
name = "migration"
version = "1.0.0"
edition = "2021"

[lib]

[dependencies]
sea-orm-migration = { version = "1.1", features = ["runtime-tokio-rustls", "sqlx-postgres", "sqlx-sqlite", "with-time"] }
async-trait = "0.1"
tracing = "0.1"
